const Product = [
    {
      "ID": 12,
      "name": "Sữa bầu Friso Mum Gold 900g hương cam",
      "oldPrice": 539000,
      "newPrice": 0,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>Thực phẩm bổ sung cho mẹ mang thai v&agrave; cho con b&uacute;, hương cam nh&atilde;n hiệu Frisomum Gold DualCare+TM<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>Friso<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Trọng lượng sản phẩm<\/td>\r\n\t\t\t<td>900g<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T22:33:37.717",
      "dateUpdate": "2024-05-28T22:46:11.740",
      "mainImg": "/uploads/product/052824103337_sua1.jpg",
      "status": 1,
      "quantity": 46,
      "sold": 4,
      "model": "Milk",
      "priority": 1,
      "categoryID": 4,
      "producerID": 7,
      "brandID": 7
    },
    {
      "ID": 13,
      "name": "Sữa Nestle S-26 ULTIMA số 3 750g (2 - 6 tuổi)",
      "oldPrice": 875000,
      "newPrice": 825000,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>Sản phẩm dinh dưỡng c&ocirc;ng thức S-26 ULTIMA 3 750G<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>Nestl&eacute;<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Sản xuất tại<\/td>\r\n\t\t\t<td>Thụy Sĩ<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Trọng lượng sản phẩm<\/td>\r\n\t\t\t<td>750g<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Độ tuổi ph&ugrave; hợp<\/td>\r\n\t\t\t<td>D&ugrave;ng cho trẻ từ 2 - 6 tuổi<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Nh&agrave; sản xuất<\/td>\r\n\t\t\t<td>Nh&agrave; m&aacute;y Konolfingen<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T22:43:03.113",
      "dateUpdate": "2024-05-28T23:13:10.653",
      "mainImg": "/uploads/product/052824104303_sua2.jpg",
      "status": 1,
      "quantity": 84,
      "sold": 16,
      "model": "Milk",
      "priority": 2,
      "categoryID": 5,
      "producerID": 6,
      "brandID": 8
    },
    {
      "ID": 14,
      "name": "Sữa Bubs Supreme Junior Nutrition 800g (3-12 tuổi)",
      "oldPrice": 780000,
      "newPrice": 0,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>Thực phẩm bổ sung Bubs Supreme Junior Nutrition<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>Bubs<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Xuất xứ thương hiệu<\/td>\r\n\t\t\t<td>&Uacute;c<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Trọng lượng sản phẩm<\/td>\r\n\t\t\t<td>800g<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Độ tuổi ph&ugrave; hợp<\/td>\r\n\t\t\t<td>D&agrave;nh cho trẻ từ 3-12 tuổi<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Nh&agrave; sản xuất<\/td>\r\n\t\t\t<td>The Infant Food Co. Pty Limited<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Hướng dẫn sử dụng<\/td>\r\n\t\t\t<td>. Rửa tay, cốc v&agrave; tất cả dụng cụ kỹ trước khi pha.<br \/>\r\n\t\t\t. Nước uống, đun s&ocirc;i nước trước khi sử dụng. Đổ lượng nước đun s&ocirc;i để nguội cần thiết v&agrave;o cốc.<br \/>\r\n\t\t\t. Th&ecirc;m nhẹ nh&agrave;ng số muỗng đong cần pha theo hướng dẫn pha, sử dụng muỗng được cung cấp v&agrave; x&acirc;y dựng theo mức độ của lon. Lu&ocirc;n cho 1 muỗng bột v&agrave;o mỗi 60ml nước.<br \/>\r\n\t\t\t. Khuấy, t&aacute;n hoặc lắc nhanh ch&oacute;ng cho đến khi tan bột. Thử nhiệt độ tại cổ tay trước khi cho ăn. Sữa n&ecirc;n ở nhiệt độ vừa ấm, kh&ocirc;ng n&oacute;ng. D&ugrave;ng ngay sau khi pha.<br \/>\r\n\t\t\tLưu &yacute;:<br \/>\r\n\t\t\t. Mỗi cốc sữa n&ecirc;n được chuẩn bị nhanh ch&oacute;ng.<br \/>\r\n\t\t\t. Nếu sữa được pha chưa được sử dụng, ch&uacute;g phải được bảo quản trong tủ lạnh v&agrave; phải sử dụng trong v&ograve;ng 24 giờ.<br \/>\r\n\t\t\t. Sản phẩm c&ograve;n thừa lại sau khi sử dụng phải đổ bỏ.<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Hướng dẫn bảo quản<\/td>\r\n\t\t\t<td>. Đ&oacute;ng chặt nắp sau mỗi lần sử dụng.<br \/>\r\n\t\t\t. Bảo quản nơi kh&ocirc; r&aacute;o, tho&aacute;ng m&aacute;t dưới 25℃.<br \/>\r\n\t\t\t. Sử dụng trong v&ograve;ng 4 tuần sau khi mở nắp.<br \/>\r\n\t\t\t. Kh&ocirc;ng sử dụng nếu m&agrave;ng seal bị thiếu hoặc hỏng.<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T22:44:24.633",
      "dateUpdate": "2024-05-31T22:38:38.733",
      "mainImg": "/uploads/product/052824104424_thuc-pham-bo-sung-bubs-supreme-junior-nutrition.png",
      "status": 1,
      "quantity": 100,
      "sold": 0,
      "model": "Supreme Junior Nutrition",
      "priority": 1,
      "categoryID": 5,
      "producerID": 7,
      "brandID": 7
    },
    {
      "ID": 15,
      "name": "Sữa non Ildong số 1 90g (0-1 tuổi)",
      "oldPrice": 299000,
      "newPrice": 249000,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>Sữa non Ildong số 1 90g (0-1 tuổi)<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>Ildong Foodis<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Sản xuất tại<\/td>\r\n\t\t\t<td>H&agrave;n Quốc<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Trọng lượng sản phẩm<\/td>\r\n\t\t\t<td>90g<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Độ tuổi ph&ugrave; hợp<\/td>\r\n\t\t\t<td>B&eacute; từ 0 - 1 tuổi<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T22:50:05.020",
      "dateUpdate": "2024-05-28T23:13:21.543",
      "mainImg": "/uploads/product/052824105005_sua3.jpg",
      "status": 1,
      "quantity": 68,
      "sold": 2,
      "model": "Milk",
      "priority": 1,
      "categoryID": 4,
      "producerID": 8,
      "brandID": 9
    },
    {
      "ID": 16,
      "name": "Vinamilk Optimum Gold 4, 850g, 2-6 tuổi",
      "oldPrice": 319000,
      "newPrice": 0,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>Vinamilk Optimum Gold 4, 850g, 2-6 tuổi<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>Optimum Gold<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Xuất xứ thương hiệu<\/td>\r\n\t\t\t<td>Việt Nam<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Sản xuất tại<\/td>\r\n\t\t\t<td>Việt Nam<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Trọng lượng sản phẩm<\/td>\r\n\t\t\t<td>850g<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Nh&agrave; sản xuất<\/td>\r\n\t\t\t<td>Vinamilk<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Độ tuổi ph&ugrave; hợp<\/td>\r\n\t\t\t<td>Trẻ từ 2 đến 6 tuổi<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T22:52:43.353",
      "dateUpdate": "2024-05-28T22:55:57.010",
      "mainImg": "/uploads/product/052824105243_sua4.jpg",
      "status": 1,
      "quantity": 99,
      "sold": 1,
      "model": "Milk",
      "priority": 1,
      "categoryID": 4,
      "producerID": 10,
      "brandID": 5
    },
    {
      "ID": 17,
      "name": "Tã quần Huggies Skincare gói cực đại (L, 9-14kg, 68 miếng)",
      "oldPrice": 319000,
      "newPrice": 0,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>T&atilde; quần Huggies Skincare g&oacute;i cực đại (L, 9-14kg, 68 miếng)<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>Huggies Skincare<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Sản xuất tại<\/td>\r\n\t\t\t<td>Việt Nam<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>K&iacute;ch cỡ (size)<\/td>\r\n\t\t\t<td>L, 9-14kg<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Số miếng<\/td>\r\n\t\t\t<td>68 miếng<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T22:58:32.857",
      "dateUpdate": "2024-05-28T23:00:09.187",
      "mainImg": "/uploads/product/052824105832_ta1.png",
      "status": 1,
      "quantity": 99,
      "sold": 1,
      "model": "Diapers",
      "priority": 1,
      "categoryID": 7,
      "producerID": 11,
      "brandID": 11
    },
    {
      "ID": 18,
      "name": "Abbott Grow",
      "oldPrice": 335000,
      "newPrice": 0,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>Sữa Abbott Grow 4 900g (tr&ecirc;n 2 tuổi)<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>ABBOTT<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Sản xuất tại<\/td>\r\n\t\t\t<td>Ireland<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Độ tuổi ph&ugrave; hợp<\/td>\r\n\t\t\t<td>Cho trẻ tr&ecirc;n 2 tuổi<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Cảnh b&aacute;o<\/td>\r\n\t\t\t<td>. Kh&ocirc;ng d&ugrave;ng l&ograve; vi s&oacute;ng để pha hay h&acirc;m n&oacute;ng v&igrave; c&oacute; thể g&acirc;y bỏng. D&ugrave;ng nhiều lần lượng pha kh&ocirc;ng đ&uacute;ng c&aacute;ch c&oacute; thể ảnh hưởng kh&ocirc;ng tốt cho sức khỏe của trẻ.<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Hướng dẫn sử dụng<\/td>\r\n\t\t\t<td>. Rửa sạch tay trước khi pha. . Cho 175ml nước ch&iacute;n để nguội v&agrave;o ly (khoảng 37&deg;C), từ từ cho v&agrave;o ly 3 muỗng gạt ngang (muỗng c&oacute; sẵn trong hộp), khuấy cho tan đều. . Uống ngay sau khi pha. Nếu kh&ocirc;ng uống ngay, n&ecirc;n đậy k&iacute;n cho v&agrave;o tủ lạnh ở 2&deg; - 4&deg;C v&agrave; d&ugrave;ng trong v&ograve;ng 24 giờ.<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Hướng dẫn bảo quản<\/td>\r\n\t\t\t<td>. Bảo quản hộp chưa sử dụng ở nhiệt độ ph&ograve;ng. Tr&aacute;nh &aacute;nh nắng trực tiếp. Khi đ&atilde; mở nắp phải được sử dụng trong v&ograve;ng 3 tuần. Đậy nắp v&agrave; bảo quản nơi kh&ocirc; m&aacute;t (kh&ocirc;ng cất trong tủ lạnh).<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T22:58:38.240",
      "mainImg": "/uploads/product/052824105838_abbott-grow-4-huong-vani-900g.jpg",
      "status": 1,
      "quantity": 3,
      "sold": 7,
      "model": "Milk",
      "priority": 2,
      "categoryID": 4,
      "producerID": 9,
      "brandID": 10
    },
    {
      "ID": 19,
      "name": "Combo 3 gói Bỉm tã quần Whito size XXL 26 miếng (13-28kg)",
      "oldPrice": 809000,
      "newPrice": 0,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>Bỉm t&atilde; quần Whito size XXL 26 miếng (13-28kg)<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>Whito<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Xuất xứ thương hiệu<\/td>\r\n\t\t\t<td>Nhật Bản<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Sản xuất tại<\/td>\r\n\t\t\t<td>Nhật Bản<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>K&iacute;ch cỡ (size)<\/td>\r\n\t\t\t<td>XXL, 13-28kg<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Số miếng<\/td>\r\n\t\t\t<td>26<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Chất liệu<\/td>\r\n\t\t\t<td>M&agrave;ng vải kh&ocirc;ng dệt, m&agrave;ng đ&aacute;y chống thấm, bột giấy, hạt thấm h&uacute;t, giấy, thun đ&agrave;n hồi, keo cấu tr&uacute;c, băng d&aacute;n.<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Nh&agrave; sản xuất<\/td>\r\n\t\t\t<td>Oji Nepia Co., Ltd.<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T23:07:37.793",
      "mainImg": "/uploads/product/052824110737_ta2.jpg",
      "status": 1,
      "quantity": 40,
      "sold": 10,
      "model": "Diapers",
      "priority": 1,
      "categoryID": 7,
      "producerID": 12,
      "brandID": 12
    },
    {
      "ID": 20,
      "name": "Thực phẩm dinh dưỡng y học Nestle Kid Essentials Nutritionally Complete 800g (1-10 tuổi)",
      "oldPrice": 809000,
      "newPrice": 0,
      "description": "<table>\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>T&ecirc;n sản phẩm<\/td>\r\n\t\t\t<td>Thực phẩm dinh dưỡng y học Kid Essentials Australia 800g hương vani (1-10 tuổi)<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Thương hiệu<\/td>\r\n\t\t\t<td>Kid Essentials<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Sản xuất tại<\/td>\r\n\t\t\t<td>Thuỵ Sĩ<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Trọng lượng sản phẩm<\/td>\r\n\t\t\t<td>800g<\/td>\r\n\t\t<\/tr>\r\n\t\t<tr>\r\n\t\t\t<td>Cảnh b&aacute;o<\/td>\r\n\t\t\t<td>. Sử dụng cho người bệnh với sự gi&aacute;m s&aacute;t của nh&acirc;n vi&ecirc;n y tế. Kh&ocirc;ng d&ugrave;ng qua đường tĩnh mạch. D&ugrave;ng nu&ocirc;i ăn bằng miệng hoặc ống th&ocirc;ng. Khi được d&ugrave;ng để nu&ocirc;i ăn bằng ống th&ocirc;ng, kh&ocirc;ng th&ecirc;m thuốc hoặc thực phẩm kh&aacute;c v&agrave;o sản phẩm.<br \/>\r\n\t\t\t. Thực phẩm cho mục đ&iacute;ch y tế đặc biệt. Liều lượng thay đổi t&ugrave;y theo nhu cầu của trẻ, l&agrave;m theo c&aacute;c khuyến nghị y tế.<\/td>\r\n\t\t<\/tr>\r\n\t<\/tbody>\r\n<\/table>\r\n",
      "datePost": "2024-05-28T23:12:47.967",
      "dateUpdate": "2024-05-31T21:49:47.157",
      "mainImg": "/uploads/product/052824111247_Food1.jpg",
      "status": 1,
      "quantity": 43,
      "sold": 7,
      "model": "Food",
      "priority": 1,
      "categoryID": 8,
      "producerID": 6,
      "brandID": 8
    }
  ]
  export default Product